"""Chat messages model added

Revision ID: 8ad6b0c33baa
Revises: e9a13d79713b
Create Date: 2024-12-25 21:28:00.939220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad6b0c33baa'
down_revision = 'e9a13d79713b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('CHATGPT', 'CLAUDE', 'CUSTOM', name='agenttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.Enum('SYSTEM', 'ASSISTANT', 'USER', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sessions', sa.Column('agent_id', sa.String(length=36), nullable=True))
    op.add_column('sessions', sa.Column('agent_state', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'agents', ['agent_id'], ['id'])
    op.add_column('topics', sa.Column('agent_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'topics', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'agent_id')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'agent_state')
    op.drop_column('sessions', 'agent_id')
    op.drop_table('chat_messages')
    op.drop_table('agents')
    # ### end Alembic commands ### 