"""Agent ai_service field

Revision ID: 0ff68e335218
Revises: 8ad6b0c33baa
Create Date: 2024-12-28 19:19:12.844183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff68e335218'
down_revision = '8ad6b0c33baa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('ai_service', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'ai_service')
    # ### end Alembic commands ### 