"""Agent Reminder message field

Revision ID: 0d71621333d6
Revises: 90c0ae5a005b
Create Date: 2024-12-30 15:58:39.787914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d71621333d6'
down_revision = '90c0ae5a005b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('reminder_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'reminder_message')
    # ### end Alembic commands ### 