"""Session is_active field

Revision ID: 90c0ae5a005b
Revises: 0ff68e335218
Create Date: 2024-12-30 15:08:13.177082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c0ae5a005b'
down_revision = '0ff68e335218'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'is_active')
    # ### end Alembic commands ### 